// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaCrud.Models;

#nullable disable

namespace NotaCrud.Migrations
{
    [DbContext(typeof(NotaContext))]
    [Migration("20260325024825_notas")]
    partial class notas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotaCrud.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("bEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("sTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("sTitulo")
                        .IsUnique();

                    b.ToTable("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
